# Generated by Django 5.0.2 on 2024-03-03 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commute.driver'),
            preserve_default=False,
        ),
    ]
