# Generated by Django 4.1.6 on 2024-03-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commute', '0002_remove_driver_car_car_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commute.car'),
            preserve_default=False,
        ),
    ]
